### PR TITLE
Updated Snowflake to v2.9.1, V2Ray to 5.15.0, removed orphaned Hysteria

### PR DESCRIPTION
**Pull request by tladesignz**
Sending you this to collaborate on.

This doesn't compile, yet, due to the following problem:

```
go/pkg/mod/github.com/apernet/quic-go@v0.32.1-0.20230226201325-e07aae1a800b/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
```

Pretty sure we're going to need Go 1.21 for latest Snowflake, which is seriously due for an update...

Any ideas?

### CODE REVIEW

**Comment by stevenmcdonald** [comment]
That looks like Hysteria? It's been a while since we updated the sub-projects, probably 9 months at least. They could probably all use an update

Hysteria is pretty straightforward, I know they refactored their code recently, at this point I don't remember if I updated to that version, I think so

V2Ray: I've been thinking of looking in to some of the other distributions of this, I'm not sure how well maintained the version we're using is, and my patching of it was amateurish at best. There are several other forks of the original project.

Lyrebird: I kinda think we should drop this. Obfs4 doesn't work with Envoy and I don't think Meek is gaining us much, not enough to make the binary bigger, since Envoy already does domain fronting

**Comment by tladesignz** [comment]
> Lyrebird: I kinda think we should drop this. Obfs4 doesn't work with Envoy and I don't think Meek is gaining us much, not enough to make the binary bigger, since Envoy already does domain fronting

I know for sure, that this doesn't create any problems to compile, so, *that* shouldn't be the reason.

Not sure if you saw it: Bitmold found a way to reduce the binary by over 50%. I added these compile flags.

But if we really don't need it, I'm fine to drop it.


I will look into updating Hysteria and V2Ray, but am happy for any insights, as you know them way better than me.

**Comment by vitriolix** [comment]
I didn't see what you are talking about with bitmold, can you link?

**Comment by tladesignz** [comment]
> I didn't see what you are talking about with bitmold, can you link?

There you go: https://github.com/stevenmcdonald/IEnvoyProxy/pull/20/files#diff-4d2a8eefdf2a9783512a35da4dc7676a66404b6f3826a8af9aad038722da6823R101-R109

**Comment by tladesignz** [comment]
Ooooooh, shiiiit. This is a huge headache-inducer.
Hysteria and V2Ray have shared dependencies but with different versions. The culprit is `gvisor`, which lacks `gvisor.dev/gvisor/pkg/bufferv2` in a later version, which V2Ray seems to force, but where Hysteria needs that file.

Seems, we're at the end of what's possible with Go mobile.

When you try to tie too many libraries together which have common but slightly different dependencies, you're basically doomed.

The go dependency management makes it more complicated on top of it:

- Hysteria wants `gvisor.dev/gvisor v0.0.0-20230401011607-0333bf067633`
- V2Ray wants `gvisor.dev/gvisor v0.0.0-20231020174304-b8a429915ff1`
- A `go mod tidy` in `IEnvoyProxy` wants to resolve to `v0.0.0-20240320123148-3c75945fd654`, no matter what Hysteria and V2Ray wants.

WTF?
This confuses me. I think I'll let this slide for now and look somewhere else.

Let me know, if you have an idea!

**Comment by stevenmcdonald** [comment]
@tladesignz Does it smooth things out if we remove v2ray (for now)? I'm fine with deprecating it while we consider the other forks of the project, or dropping it altogether. I think it's also the biggest thing we're pulling in. I'd kind of like to look at WebTunnel too... some of the PTs work for us and some of them just don't play well with Envoy (obfs4 for example)

> Not sure if you saw it: Bitmold found a way to reduce the binary by over 50%. I added these compile flags.

I had not seen that, that's awesome!

**Comment by tladesignz** [comment]
Ahaha!
Hysteria removed and all the necessary workarounds it induced, and suddenly everything compiles.
For Android and iOS/macOS, no problem.

Please review and merge!

**Comment by tladesignz** [comment]
For context: Hysteria 1 is discontinued. There was one patch update available, but that changed nothing.
V2Ray-core, on the other hand got some love, recently, so that one doesn't induce any issues.

Hysteria v2 seems to have massively changed. (They say, it's almost a  full rewrite.)
So I suggest, we just remove it here, first.
And then start looking into bringing Hysteria v2 back, if need be and if it doesn't break anything.

**Comment by mnbogner** [comment]
> Hysteria

Do we also need to make an update to Envoy to remove Hysteria support or is the plan to integrate Hysteria v2 before we do another IEnvoyProxy release?

**Comment by stevenmcdonald** [comment]
Thanks for the updates @tladesignz and it's nice to see the iOS stuff get some attention too

**Pull request merged**
